
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: GarthsList_development
test:
  <<: *default
  database: GarthsList_test
production:
  <<: *default
  database: GarthsList_production
  password: <%= ENV['GARTHSLIST_DATABASE_PASSWORD'] %>
